services:
  - type: web
    name: mobile-store-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
