"""Update Product model brand field

Revision ID: 571dee0ef261
Revises: 
Create Date: 2025-08-28 16:28:21.808012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571dee0ef261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))

        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
